### ISSUE TITLE
How do I send Data from the coordinator to router 

### ISSUE THREAD

**Issue by AbassLanre** [reasyrf/XBeeMultiTerminal#1]
I am doing a project that involves me sending data from my PC to a notice board using ZigBee devices, can your terminal do this after setting the ZigBee modules in AT or API mode

**Comment by bleckers** [comment]
This is typically for use as a multiplexed terminal system:

https://raw.githubusercontent.com/reasyrf/XBeeMultiTerminal/master/docs/media/Hardware.png

Basically the way it works is it splits the data outputs from a single GUI interface (or multiple named PIPEs) to multiple different devices based on their MAC.
For this splitting to work, the device connected to the host/basestation PC needs to be in API mode (so it can get the transmitter address and the data). The remote devices need to be in transparent mode as they are emulating a terminal UART interface.
